### ISSUE TITLE
Broken doi link at top of repo home page

### ISSUE THREAD

**Issue by brianzelip** [1heidi/nar#1]
Hi Heidi - just a quick fyi that the doi link under the About section at the top of this repo's home page is broken.

To fix, remove the dot at the very end

doi.org/10.3389/frma.2018.00018.

doi.org/10.3389/frma.2018.00018

**Comment by 1heidi** [comment]
Thanks, Brian!  I didn't an alert for this and wasn't paying attention. Sorry for the delayed response! It's fixed!
